/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import swing.table.tbCustom.ScrollBar;
import java.awt.Color;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import swing.model.StatusType;

/**
 *
 * @author sethk
 */
public class FormDatSan extends javax.swing.JPanel {
    DefaultTableModel model;
    /**
     * Creates new form FormDatSan
     */
    public FormDatSan() {
        initComponents();
        spTable.setVerticalScrollBar(new ScrollBar());
        spTable.getVerticalScrollBar().setBackground(Color.WHITE);
        spTable.getViewport().setBackground(Color.WHITE);
        JPanel p = new JPanel();
        p.setBackground(Color.WHITE);
        spTable.setCorner(JScrollPane.UPPER_RIGHT_CORNER, p);
        model = (DefaultTableModel) tbDatSan.getModel();
        model.setRowCount(0);
        model.addRow(new Object[]{"NouCamp", "Sân 11", StatusType.REJECT});
        model.addRow(new Object[]{"NouCamp", "Sân 11", StatusType.REJECT});
        model.addRow(new Object[]{"NouCamp", "Sân 11", StatusType.REJECT});
        model.addRow(new Object[]{"NouCamp", "Sân 11", StatusType.REJECT});
        model.addRow(new Object[]{"NouCamp", "Sân 11", StatusType.REJECT});
        model.addRow(new Object[]{"NouCamp", "Sân 11", StatusType.REJECT});
        model.addRow(new Object[]{"NouCamp", "Sân 11", StatusType.REJECT});
        model.addRow(new Object[]{"NouCamp", "Sân 11", StatusType.REJECT});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spTable = new javax.swing.JScrollPane();
        tbDatSan = new com.raven.swing.Table();

        setBackground(new java.awt.Color(255, 255, 255));

        tbDatSan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spTable.setViewportView(tbDatSan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(585, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(spTable, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane spTable;
    private com.raven.swing.Table tbDatSan;
    // End of variables declaration//GEN-END:variables
}
