/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author sethk
 */
public class FormGiaoCa extends javax.swing.JPanel {

    /**
     * Creates new form FormGiaoCA
     */
    public FormGiaoCa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSeth1 = new swing.component.PanelSeth();
        panelSeth2 = new swing.component.PanelSeth();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.GridLayout(1, 0));

        panelSeth1.setColor1(new java.awt.Color(142, 142, 250));
        panelSeth1.setColor2(new java.awt.Color(123, 123, 245));

        javax.swing.GroupLayout panelSeth1Layout = new javax.swing.GroupLayout(panelSeth1);
        panelSeth1.setLayout(panelSeth1Layout);
        panelSeth1Layout.setHorizontalGroup(
            panelSeth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        panelSeth1Layout.setVerticalGroup(
            panelSeth1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        add(panelSeth1);

        panelSeth2.setColor1(new java.awt.Color(186, 123, 247));
        panelSeth2.setColor2(new java.awt.Color(123, 123, 245));

        javax.swing.GroupLayout panelSeth2Layout = new javax.swing.GroupLayout(panelSeth2);
        panelSeth2.setLayout(panelSeth2Layout);
        panelSeth2Layout.setHorizontalGroup(
            panelSeth2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );
        panelSeth2Layout.setVerticalGroup(
            panelSeth2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );

        add(panelSeth2);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.component.PanelSeth panelSeth1;
    private swing.component.PanelSeth panelSeth2;
    // End of variables declaration//GEN-END:variables
}
